# Site settings
title: Diego Fernandes
email: diego.schell.f@gmail.com
url: https://diego3g.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Diego Fernandes

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://www.fb.com/diego.schell.fernandes
  - title: instagram
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/diego
  - title: skype
    url: http://github.com/diego3g

# Build settings
markdown: kramdown
permalink: pretty
