# Site settings
title: Diego Fernandes
email: diego.schell.f@gmail.com
url: https://diego3g.github.io
description: "Frontend Web Developer, Javacript, Hybrid Mobile, Node and UX Design lover."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: d40612 #80B3FF
  secondary: 333333 #FD6E8A
  secondary-dark: 222222 #A2122F

# Footer settings
footer:
  copyright: Diego Fernandes

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://www.fb.com/diego.schell.fernandes
  - title: instagram
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/diego
  - title: skype
    url: "skype:kbutow"

# Build settings
markdown: kramdown
permalink: pretty